# Generated by Django 2.1.7 on 2019-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
